### ISSUE TITLE
Wrong links

### ISSUE THREAD

**Issue by T1mL3arn** [joshtynjala/optimizing-performance-for-the-flash-platform#1]
Links in this doc https://github.com/joshtynjala/optimizing-performance-for-the-flash-platform/blob/main/conserving-memory/index.md are lead to missing html files.

**Comment by joshtynjala** [comment]
I am aware. I have not finished my conversion yet.

**Comment by T1mL3arn** [comment]
Well, I am closing the issue then :sweat_smile:

**Comment by joshtynjala** [comment]
@T1mL3arn The links should all be working now!
